---
title: "População e Frota de Veículos"
author: "Mario Azevedo"
date: "Sunday, May 24, 2015"
output:
  html_document:
    keep_md: yes
  word_document: default
---

###Carregando as bibliotecas necessárias

```{r, message=FALSE, warning=FALSE}
library(data.table)
library(dplyr)
library(pander)
library(knitr)
library(stringr)
options(scipen=1, digits=2, width=120)
```

###Lendo os dados

```{r}
dados <- fread('FrotaBR122013.csv',sep=';')
estados <- fread('estados.csv',sep=';')
estados <- mutate(estados,CAPITAL=str_trim(CAPITAL))
estados <- mutate(estados,ESTADO=str_trim(ESTADO))
str(dados)
str(estados)
estados
```

###Características Gerais

1. Número de municípios, população e frota total, de automóveis e motocicletas por estado

```{r}
tabela <- group_by(dados,UF) %>%
        summarise(Nmun = n(),
                  Populacao = sum(POPULACAO),
                  Veiculos = sum(TOTAL),
                  Automoveis = sum(AUTOMOVEL),
                  Motocicletas = sum(MOTOCICLETA))

kable(tabela)
```

2. População e frota total, de automóveis e motocicletas da capitais

```{r}
tabela <- filter(dados,MUNICIPIO %in% estados$CAPITAL) %>% 
        mutate(CAPITAL = MUNICIPIO) %>%
        select (CAPITAL,UF,POPULACAO,TOTAL,AUTOMOVEL) %>%
        mutate (APM = 1000*AUTOMOVEL/POPULACAO) %>%
        arrange (desc(APM))

kable(tabela)
```

