---
title: "Frota de Veículos do Brasil - abril de 2015"
author: "Mario Azevedo"
date: "Sexta, 29/05/2015"
output:
  html_document:
    keep_md: yes
  pdf_document: default
  word_document: default
---

###Carregando as bibliotecas necessárias

```{r, message=FALSE, warning=FALSE}
library(data.table)
library(dplyr)
library(stringr)
library(knitr)
library(pander)
library(ggplot2)
options(scipen=1, digits=2, width=105)
```

###Lendo os dados


```{r}
#fileURL <- "http://www.denatran.gov.br/download/frota/Frota_por_Municipio_e_Tipo-ABR_15.rar"
#localfilename <- "Frota_por_Municipio_e_Tipo-ABR_15.rar"
#download.file(fileURL,localfilename,mode='wb')

dados <- fread('Frota_por_Municipio_e_Tipo-ABR_15.csv',sep=';')
cidades <- fread('estimativas_dou_2014_xls.csv',sep=';')
sum(dados$TOTAL)
nrow(dados)
cidades <- mutate(cidades,NOME_MUN = str_to_upper(iconv(NOME_MUN,to = "ASCII//TRANSLIT")))
arrange(cidades[!(cidades$NOME_MUN %in% dados$MUNICIPIO)],UF)
arrange(dados[!(dados$MUNICIPIO %in% cidades$NOME_MUN)],UF)
```

###Frota dos estados

```{r}
tabela <- group_by(dados,UF) %>%
        summarise(Nmun = n(),
                  Veiculos = sum(TOTAL),
                  Automoveis = sum(AUTOMOVEL),
                  Caminhoes=sum(CAMINHAO),
                  Onibus=sum(ONIBUS),
                  Motocicletas=sum(MOTOCICLETA))
kable(tabela)
nrow(tabela)
```

